### ISSUE TITLE
bits/s and bytes/s was confused in the benchmark output

### ISSUE THREAD

**Issue by leo-yuriev** [flier/rust-t1ha#3]

**Comment by flier** [comment]
I think GiB/s is ok, it's a abbr for [Gibibyte](https://en.wikipedia.org/wiki/Gibibyte), the bits/s should be [Gibit](https://en.wikipedia.org/wiki/Gibibit), what's your suggestion?

**Comment by leo-yuriev** [comment]
I meant you should multiply the result by 8 (for bits per second instead of bytes per second).

**Comment by flier** [comment]
In fact, the output report was generated by the benchmark library [criterion.rs](https://github.com/bheisler/criterion.rs), it only support two [Throughput](https://bheisler.github.io/criterion.rs/criterion/enum.Throughput.html) mode: `Bytes` and `Elements`.

Maybe I can submit a PR to add a new `Bits` mode later.

**Comment by leo-yuriev** [comment]
I think, it no matter to output the results in bits or bytes. The main thing is that the numbers are _correct_ and _matches_ to the units of measurement.

**Comment by flier** [comment]
Sorry, it seems I misunderstand your meaning, could you help to point out my mistake?

In the benchmark, I use a pre-generated byte array `DATA` which is `16KB` as input, the `t1ha1` function will hash the slice (`&DATA[..size]`) with a `SEED`. It means every test cycle we will handle `size` bytes, right? 
 The `size` come from the `PARAMS` from 7 bytes to 16 KB, and it should be pass to`Throughput::Bytes`.

I'm following the [Throughput Measurements](https://bheisler.github.io/criterion.rs/book/user_guide/advanced_configuration.html#throughput-measurements) section from `criterion.rs` user guide.

> When benchmarking some types of code it is useful to measure the throughput as well as the iteration time, either in bytes per second or elements per second. Criterion.rs can estimate the throughput of a benchmark, but it needs to know how many bytes or elements each iteration will process.

```rust
const KB: usize = 1024;
const SEED: u64 = 0x0123456789ABCDEF;
const PARAMS: [usize; 11] = [7, 8, 32, 64, 256, 512, KB, 2 * KB, 4 * KB, 8 * KB, 16 * KB];

lazy_static! {
    static ref DATA: Vec<u8> = (0..16 * KB).map(|b| b as u8).collect::<Vec<_>>();
}

fn bench_t1ha(c: &mut Criterion) {
    c.bench(
        "t1ha1",
        ParameterizedBenchmark::new(
            "t1ha1",
            move |b, &&size| {
                b.iter(|| t1ha1(&DATA[..size], SEED));
            },
            &PARAMS,
        )
        .throughput(|&&size| Throughput::Bytes(size as u32)),
    );
}
```

So, do you means I misuse the benchmark? or you concern the test result is wrong?

I compared the result with [smhasher suite](https://github.com/rurban/smhasher), the result is inequality (different implementation and different test cases) but seems still at same order of magnitude

For example, smhasher give the throughput with MiB/sec

| Hash function                         |      MiB/sec  |cycles/hash| Quality problems              |
|:--------------------------------------|--------------:|---------:|--------------------------------|
| [SipHash13](doc/SipHash13)            |     1865.13	|   100.55 | 0.9% bias                  |
| [metrohash64_1](doc/metrohash64_1)    |      9541.68	|    50.85 |                            |
| [metrohash64_2](doc/metrohash64_2)    |      9569.20	|    50.86 |                            |
| [metrohash128_1](doc/metrohash128_1)  |      9908.72	|    81.39 |                            |
| [metrohash128_2](doc/metrohash128_2)  |      9943.95	|    81.31 |                            |
| [t1ha_64be](doc/t1ha_64be)            |      7146.84	|    39.78 |                            |
| [t1ha_32le](doc/t1ha_32le)            |      5577.12	|    42.53 |                            |

And I got the throughput with GiB/s (Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz)

```
$ RUSTFLAGS='-C target-cpu=native' cargo +nightly bench sip metro t1ha1 t1ha0_32
hash64/siphash/4096     time:   [1.8637 us 1.8838 us 1.9166 us]
                        thrpt:  [1.9903 GiB/s 2.0250 GiB/s 2.0468 GiB/s]

$ RUSTFLAGS='-C target-cpu=native' cargo +nightly bench metro
hash64/metrohash64/4096 time:   [323.43 ns 331.12 ns 341.72 ns]
                        thrpt:  [11.163 GiB/s 11.521 GiB/s 11.794 GiB/s]
hash128/metrohash128/4096
                        time:   [313.91 ns 317.90 ns 322.43 ns]
                        thrpt:  [11.831 GiB/s 12.000 GiB/s 12.152 GiB/s]

$ RUSTFLAGS='-C target-cpu=native' cargo +nightly bench t1ha1
hash64/t1ha1/4096       time:   [282.23 ns 288.51 ns 297.83 ns]
                        thrpt:  [12.808 GiB/s 13.222 GiB/s 13.516 GiB/s]

$ RUSTFLAGS='-C target-cpu=native' cargo +nightly bench t1ha0_32
hash32/t1ha0_32/4096    time:   [494.75 ns 495.88 ns 497.23 ns]
                        thrpt:  [7.6718 GiB/s 7.6928 GiB/s 7.7104 GiB/s]
```

**Comment by flier** [comment]
In fact, it can [achieve 40 GiB/s](https://www.reddit.com/r/rust/comments/ayla9m/rust_implementation_for_t1ha_fast_positive_hash/) with AVX2 on my laptop, and 13 GiB/s without AES.

I think the result is reasonable, right?

```
$ RUST_BACKTRACE=full RUSTFLAGS="-C target-cpu=native" cargo +nightly bench t1ha0_ia32aes_avx2
hash64/t1ha0_ia32aes_avx2/4096
                        time:   [90.588 ns 91.618 ns 92.835 ns]
                        thrpt:  [41.091 GiB/s 41.637 GiB/s 42.110 GiB/s]

$ RUST_BACKTRACE=full RUSTFLAGS="-C target-cpu=native" cargo +nightly bench t1ha1
hash64/t1ha1/4096       time:   [290.88 ns 293.01 ns 295.28 ns]
                        thrpt:  [12.919 GiB/s 13.019 GiB/s 13.114 GiB/s]

$ RUST_BACKTRACE=full RUSTFLAGS="-C target-cpu=native" cargo +nightly bench DefaultHasher
hash64/hash_map::DefaultHasher/4096
                        time:   [1.0750 us 1.0831 us 1.0912 us]
                        thrpt:  [3.4959 GiB/s 3.5220 GiB/s 3.5485 GiB/s]

$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

$ rustc -V
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by leo-yuriev** [comment]
Not GiB/s, but GB/s :)

**Comment by leo-yuriev** [comment]
Sorry, it my mistake.

Historically In Russian "GiB" some time mean "giga bit", but not modern "gibyte" )

**Comment by flier** [comment]
No problem, it's a cultural difference, I just follow [the Wiki definition](https://en.wikipedia.org/wiki/Gibibyte) :)
